### ISSUE TITLE
issue about destroy glcomponent

### ISSUE THREAD

**Issue by SangJuBaek** [emedware/vue-golden-layout#87]
I'm sorry to bother you.

Could you tell me how the error handling of [this issue](https://github.com/emedware/vue-golden-layout/issues/82) is going?

**Comment by eddow** [comment]
Oh - sorry - I guess one has no notifications when the bug is closed.
Well, please describe what you mean by "when I tried to destroy the gl-component" - here, I closed all the closable documents and had no bugs.
Which gl-compenent are you trying to destroy? Did you add code in the demo ? If yes, could you share it ?

**Comment by SangJuBaek** [comment]
Oh, I'm sorry. The error in the screen shot is the error that occurs when the demo-stack is closed, not gl-component. My mistake.

Actually, the problem I am currently experiencing occurs when the @destroy callback of gl-component is called.

I saved the data to draw the gl-component inside the stack in the vuex store. And if I closed the gl-component, I tried to remove the data that made up that gl-component from the store through @destory callback. But after the initial normal removal, the @destoy callback is called back. At this time, an attempt is made to erase another gl-component in the same stack that is not subject to the destroy.

I tried to make a demo through the code sandbox, but errors such as the screenshot attached are occurring. Other vue-golden-layout examples of code sandbox are experiencing the same error. I think I can't deliver an example through this.

![sandboxError](https://user-images.githubusercontent.com/6037505/93044434-d86d0100-f68f-11ea-956b-243e3d9c2db6.png)

Have you ever seen a case like this?

If an example of the current situation is needed, how should it be communicated?

**Comment by eddow** [comment]
I really tried several time unsuccessfully to find out the bug or even a case where @destroy is called twice on a component.
A sand-box with the error would definitely greatly help.

**Comment by SangJuBaek** [comment]
I tried to provide a sandbox, but I couldn't because there was an error like a screenshot.
![goldenlayout](https://user-images.githubusercontent.com/6037505/98519379-0a779980-22b4-11eb-841f-c8633b26d2d6.png)
How should I hand over the code to you?

**Comment by SangJuBaek** [comment]
I finally figured out which part was the problem.
My source manages data about gl-components in the form of json objects in the vuex store and draws it on the screen via v-for in the template.
If you click the close button of the header, you are riding the flow as follows, as I have roughly identified.

![goldenLayout](https://user-images.githubusercontent.com/6037505/102740575-896fef80-4393-11eb-9627-b97fc7d46b51.png)

Within the callback function for 'remove child callback' (Our web), I'm splicing data about the data in the vuex store that should be closed. (red box)
When this is done, it seems that the deletion logic is called again by calling 'destroyed hook' (blue line)

Is there any way I can handle this part?
If this usage is wrong, could you tell me what other methods I should use?

**Comment by SangJuBaek** [comment]
The part that calls'remove child callback' is'_$destory(Stack)'.
It is not'remove child(component)'.
I'm sorry. It's my mistake.

**Comment by SangJuBaek** [comment]
I corrected the wrong part.

![goldenLayout](https://user-images.githubusercontent.com/6037505/102833746-4f572a00-4435-11eb-86b7-d4e4835a3f5f.png)

**Comment by hartum** [comment]
I also tried to upload an example to codesandbox and got the same error:
![download-1](https://user-images.githubusercontent.com/51665/105902391-e0b25100-601e-11eb-941d-01aa90a7fa22.png)

So if you don't mind, I've prepared a zip file with a super basic example, [here](https://drive.google.com/file/d/1aQmwRIYxZu3cgpBMjUYyBZ0QnSND8FFT/view?usp=sharing)

After running you will see a screen like that:
![download-2](https://user-images.githubusercontent.com/51665/105903017-abf2c980-601f-11eb-9fe0-d68f695c2f38.png)

Just press the button and see the error in console.

**Comment by eddow** [comment]
I finally found the origin of the error.

Indeed, the "destroy stack 2" I don't know why, destroys *both* the stacks.

It seems that it occurs when the stacks container (here the `gl-row`) is the *root* of the layout.
For now, I can only advise you a workaround by putting the `gl-row` in a `gl-col` who contains only this element

**Comment by ken-xxx** [comment]
@eddow  i have the same problem, how do I fix it?

**Comment by leeooooooooo** [comment]
@eddow +1
it's still happening.
I would like to know the current status of this issue.

**Comment by eddow** [comment]
> For now, I can only advise you a workaround by putting the `gl-row` in a `gl-col` who contains only this element

The solution is really cost-less - and the problem is too bizarre to make it a priority
